
services:
  fastapi:
    image: fastapi
    build: .
    container_name: fastapi-dev
    restart: always
    tty: true
    volumes:
      - ./:/code
    ports:
      - "8001:8000"
    # develop:
    #   watch:
    #     - path: ./Dockerfile
    #       action: rebuild
    #     - path: ./dock-compose.yml
    #       action: rebuild
    #     - path: ./requirements.txt
    #       action: restart

      
  #   environment:
  #     DB_HOST: db
  #     DB_NAME: fastapi
  #     DB_USER: fastapi
  #     DB_PASSWORD: fastapi
  #   depends_on:
  #     db-fastapi:
  #       condition: service_healthy

  # db-fastapi:
  #   image: postgres:17-alpine
  #   container_name: postgres-fastapi
  #   restart: always
  #   environment:
  #     POSTGRES_DB: fastapi
  #     POSTGRES_USER: fastapi
  #     POSTGRES_PASSWORD: fastapi
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  #   ports:
  #     - "5433:5432"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U produser -d proddb"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
