services:
  app:
    image: fastapi
    build: .
    container_name: fastapi-app
    restart: always
    volumes:
      - ./src:/code/src
      - ./alembic:/code/alembic
      - ./alembic.ini:/code/alembic.ini
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    container_name: fastapi-db
    restart: always
    environment:
      POSTGRES_DB: fastapi
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: fastapi
      TZ: Asia/Shanghai
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fastapi -d fastapi"]
      interval: 5s
      timeout: 5s
      retries: 5
