services:
  app:
    image: fastapi
    build: .
    container_name: fastapi-app
    restart: always
    volumes:
      - ./src:/code
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: timescale/timescaledb:latest-pg17
    container_name: fastapi-db
    restart: always
    environment:
      POSTGRES_DB: fastapi
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: fastapi
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fastapi -d fastapi"]
      interval: 5s
      timeout: 5s
      retries: 5
