"""add a column to User

Revision ID: bdf0668801a2
Revises: 387403ab6b58
Create Date: 2025-06-04 16:09:38.540768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bdf0668801a2'
down_revision: Union[str, None] = '387403ab6b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=18), nullable=False))
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=128),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('user', 'username',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
